/*
Authentication And Authorization (AAA) Service

This swagger documentation provides all AAA API details. AAA service provides authentication and authorization capabilities for users.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aaadomain

import (
	"encoding/json"
)

// PutErrorResponse struct for PutErrorResponse
type PutErrorResponse struct {
	Error *Error `json:"error,omitempty"`
	Request *Request `json:"request,omitempty"`
	Data *SuccessResponseAllOfData `json:"data,omitempty"`
}

// NewPutErrorResponse instantiates a new PutErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutErrorResponse() *PutErrorResponse {
	this := PutErrorResponse{}
	return &this
}

// NewPutErrorResponseWithDefaults instantiates a new PutErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutErrorResponseWithDefaults() *PutErrorResponse {
	this := PutErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PutErrorResponse) GetError() Error {
	if o == nil || isNil(o.Error) {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutErrorResponse) GetErrorOk() (*Error, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PutErrorResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *PutErrorResponse) SetError(v Error) {
	o.Error = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *PutErrorResponse) GetRequest() Request {
	if o == nil || isNil(o.Request) {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutErrorResponse) GetRequestOk() (*Request, bool) {
	if o == nil || isNil(o.Request) {
    return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *PutErrorResponse) HasRequest() bool {
	if o != nil && !isNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *PutErrorResponse) SetRequest(v Request) {
	o.Request = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PutErrorResponse) GetData() SuccessResponseAllOfData {
	if o == nil || isNil(o.Data) {
		var ret SuccessResponseAllOfData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutErrorResponse) GetDataOk() (*SuccessResponseAllOfData, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PutErrorResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SuccessResponseAllOfData and assigns it to the Data field.
func (o *PutErrorResponse) SetData(v SuccessResponseAllOfData) {
	o.Data = &v
}

func (o PutErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !isNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePutErrorResponse struct {
	value *PutErrorResponse
	isSet bool
}

func (v NullablePutErrorResponse) Get() *PutErrorResponse {
	return v.value
}

func (v *NullablePutErrorResponse) Set(val *PutErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePutErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePutErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutErrorResponse(val *PutErrorResponse) *NullablePutErrorResponse {
	return &NullablePutErrorResponse{value: val, isSet: true}
}

func (v NullablePutErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


