/*
Authentication And Authorization (AAA) Service

This swagger documentation provides all AAA API details. AAA service provides authentication and authorization capabilities for users.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aaadomain

import (
	"encoding/json"
)

// SMSSendRequestReq struct for SMSSendRequestReq
type SMSSendRequestReq struct {
	Ip *string `json:"ip,omitempty"`
	UserAgent *string `json:"user-agent,omitempty"`
}

// NewSMSSendRequestReq instantiates a new SMSSendRequestReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSMSSendRequestReq() *SMSSendRequestReq {
	this := SMSSendRequestReq{}
	return &this
}

// NewSMSSendRequestReqWithDefaults instantiates a new SMSSendRequestReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSMSSendRequestReqWithDefaults() *SMSSendRequestReq {
	this := SMSSendRequestReq{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *SMSSendRequestReq) GetIp() string {
	if o == nil || isNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMSSendRequestReq) GetIpOk() (*string, bool) {
	if o == nil || isNil(o.Ip) {
    return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *SMSSendRequestReq) HasIp() bool {
	if o != nil && !isNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *SMSSendRequestReq) SetIp(v string) {
	o.Ip = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *SMSSendRequestReq) GetUserAgent() string {
	if o == nil || isNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMSSendRequestReq) GetUserAgentOk() (*string, bool) {
	if o == nil || isNil(o.UserAgent) {
    return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *SMSSendRequestReq) HasUserAgent() bool {
	if o != nil && !isNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *SMSSendRequestReq) SetUserAgent(v string) {
	o.UserAgent = &v
}

func (o SMSSendRequestReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !isNil(o.UserAgent) {
		toSerialize["user-agent"] = o.UserAgent
	}
	return json.Marshal(toSerialize)
}

type NullableSMSSendRequestReq struct {
	value *SMSSendRequestReq
	isSet bool
}

func (v NullableSMSSendRequestReq) Get() *SMSSendRequestReq {
	return v.value
}

func (v *NullableSMSSendRequestReq) Set(val *SMSSendRequestReq) {
	v.value = val
	v.isSet = true
}

func (v NullableSMSSendRequestReq) IsSet() bool {
	return v.isSet
}

func (v *NullableSMSSendRequestReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSMSSendRequestReq(val *SMSSendRequestReq) *NullableSMSSendRequestReq {
	return &NullableSMSSendRequestReq{value: val, isSet: true}
}

func (v NullableSMSSendRequestReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSMSSendRequestReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


