/*
Authentication And Authorization (AAA) Service

This swagger documentation provides all AAA API details. AAA service provides authentication and authorization capabilities for users.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aaadomain

import (
	"encoding/json"
)

// GroupChangeAllOf struct for GroupChangeAllOf
type GroupChangeAllOf struct {
	Cdc GroupResponse `json:"cdc"`
}

// NewGroupChangeAllOf instantiates a new GroupChangeAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChangeAllOf(cdc GroupResponse) *GroupChangeAllOf {
	this := GroupChangeAllOf{}
	this.Cdc = cdc
	return &this
}

// NewGroupChangeAllOfWithDefaults instantiates a new GroupChangeAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChangeAllOfWithDefaults() *GroupChangeAllOf {
	this := GroupChangeAllOf{}
	return &this
}

// GetCdc returns the Cdc field value
func (o *GroupChangeAllOf) GetCdc() GroupResponse {
	if o == nil {
		var ret GroupResponse
		return ret
	}

	return o.Cdc
}

// GetCdcOk returns a tuple with the Cdc field value
// and a boolean to check if the value has been set.
func (o *GroupChangeAllOf) GetCdcOk() (*GroupResponse, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Cdc, true
}

// SetCdc sets field value
func (o *GroupChangeAllOf) SetCdc(v GroupResponse) {
	o.Cdc = v
}

func (o GroupChangeAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cdc"] = o.Cdc
	}
	return json.Marshal(toSerialize)
}

type NullableGroupChangeAllOf struct {
	value *GroupChangeAllOf
	isSet bool
}

func (v NullableGroupChangeAllOf) Get() *GroupChangeAllOf {
	return v.value
}

func (v *NullableGroupChangeAllOf) Set(val *GroupChangeAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChangeAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChangeAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChangeAllOf(val *GroupChangeAllOf) *NullableGroupChangeAllOf {
	return &NullableGroupChangeAllOf{value: val, isSet: true}
}

func (v NullableGroupChangeAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChangeAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


