/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// TenantCallbackResponse struct for TenantCallbackResponse
type TenantCallbackResponse struct {
	// tenant id.
	TenantId *string `json:"tenantId,omitempty"`
	Status *CallbackStatus `json:"status,omitempty"`
	// failure reason in case of execution is failed.
	Reason *string `json:"reason,omitempty"`
	// request data
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewTenantCallbackResponse instantiates a new TenantCallbackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCallbackResponse() *TenantCallbackResponse {
	this := TenantCallbackResponse{}
	return &this
}

// NewTenantCallbackResponseWithDefaults instantiates a new TenantCallbackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCallbackResponseWithDefaults() *TenantCallbackResponse {
	this := TenantCallbackResponse{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *TenantCallbackResponse) GetTenantId() string {
	if o == nil || o.TenantId == nil {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCallbackResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || o.TenantId == nil {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *TenantCallbackResponse) HasTenantId() bool {
	if o != nil && o.TenantId != nil {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *TenantCallbackResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TenantCallbackResponse) GetStatus() CallbackStatus {
	if o == nil || o.Status == nil {
		var ret CallbackStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCallbackResponse) GetStatusOk() (*CallbackStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TenantCallbackResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CallbackStatus and assigns it to the Status field.
func (o *TenantCallbackResponse) SetStatus(v CallbackStatus) {
	o.Status = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *TenantCallbackResponse) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCallbackResponse) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *TenantCallbackResponse) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *TenantCallbackResponse) SetReason(v string) {
	o.Reason = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TenantCallbackResponse) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCallbackResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TenantCallbackResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *TenantCallbackResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o TenantCallbackResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TenantId != nil {
		toSerialize["tenantId"] = o.TenantId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableTenantCallbackResponse struct {
	value *TenantCallbackResponse
	isSet bool
}

func (v NullableTenantCallbackResponse) Get() *TenantCallbackResponse {
	return v.value
}

func (v *NullableTenantCallbackResponse) Set(val *TenantCallbackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCallbackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCallbackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCallbackResponse(val *TenantCallbackResponse) *NullableTenantCallbackResponse {
	return &NullableTenantCallbackResponse{value: val, isSet: true}
}

func (v NullableTenantCallbackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCallbackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


