/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// StateMachineConfig Container type state-machine configuration
type StateMachineConfig struct {
	States States `json:"states"`
}

// NewStateMachineConfig instantiates a new StateMachineConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStateMachineConfig(states States) *StateMachineConfig {
	this := StateMachineConfig{}
	this.States = states
	return &this
}

// NewStateMachineConfigWithDefaults instantiates a new StateMachineConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStateMachineConfigWithDefaults() *StateMachineConfig {
	this := StateMachineConfig{}
	return &this
}

// GetStates returns the States field value
func (o *StateMachineConfig) GetStates() States {
	if o == nil {
		var ret States
		return ret
	}

	return o.States
}

// GetStatesOk returns a tuple with the States field value
// and a boolean to check if the value has been set.
func (o *StateMachineConfig) GetStatesOk() (*States, bool) {
	if o == nil {
    return nil, false
	}
	return &o.States, true
}

// SetStates sets field value
func (o *StateMachineConfig) SetStates(v States) {
	o.States = v
}

func (o StateMachineConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["states"] = o.States
	}
	return json.Marshal(toSerialize)
}

type NullableStateMachineConfig struct {
	value *StateMachineConfig
	isSet bool
}

func (v NullableStateMachineConfig) Get() *StateMachineConfig {
	return v.value
}

func (v *NullableStateMachineConfig) Set(val *StateMachineConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableStateMachineConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableStateMachineConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStateMachineConfig(val *StateMachineConfig) *NullableStateMachineConfig {
	return &NullableStateMachineConfig{value: val, isSet: true}
}

func (v NullableStateMachineConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStateMachineConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


