/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// ContainerTypeChangeLogResponse struct for ContainerTypeChangeLogResponse
type ContainerTypeChangeLogResponse struct {
	Error *Error `json:"error,omitempty"`
	Data *ContainerTypeChangeLogResponseData `json:"data,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewContainerTypeChangeLogResponse instantiates a new ContainerTypeChangeLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerTypeChangeLogResponse() *ContainerTypeChangeLogResponse {
	this := ContainerTypeChangeLogResponse{}
	return &this
}

// NewContainerTypeChangeLogResponseWithDefaults instantiates a new ContainerTypeChangeLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerTypeChangeLogResponseWithDefaults() *ContainerTypeChangeLogResponse {
	this := ContainerTypeChangeLogResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ContainerTypeChangeLogResponse) GetError() Error {
	if o == nil || isNil(o.Error) {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerTypeChangeLogResponse) GetErrorOk() (*Error, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ContainerTypeChangeLogResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *ContainerTypeChangeLogResponse) SetError(v Error) {
	o.Error = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ContainerTypeChangeLogResponse) GetData() ContainerTypeChangeLogResponseData {
	if o == nil || isNil(o.Data) {
		var ret ContainerTypeChangeLogResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerTypeChangeLogResponse) GetDataOk() (*ContainerTypeChangeLogResponseData, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ContainerTypeChangeLogResponse) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ContainerTypeChangeLogResponseData and assigns it to the Data field.
func (o *ContainerTypeChangeLogResponse) SetData(v ContainerTypeChangeLogResponseData) {
	o.Data = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ContainerTypeChangeLogResponse) GetRequest() Request {
	if o == nil || isNil(o.Request) {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerTypeChangeLogResponse) GetRequestOk() (*Request, bool) {
	if o == nil || isNil(o.Request) {
    return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ContainerTypeChangeLogResponse) HasRequest() bool {
	if o != nil && !isNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *ContainerTypeChangeLogResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o ContainerTypeChangeLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !isNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullableContainerTypeChangeLogResponse struct {
	value *ContainerTypeChangeLogResponse
	isSet bool
}

func (v NullableContainerTypeChangeLogResponse) Get() *ContainerTypeChangeLogResponse {
	return v.value
}

func (v *NullableContainerTypeChangeLogResponse) Set(val *ContainerTypeChangeLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerTypeChangeLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerTypeChangeLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerTypeChangeLogResponse(val *ContainerTypeChangeLogResponse) *NullableContainerTypeChangeLogResponse {
	return &NullableContainerTypeChangeLogResponse{value: val, isSet: true}
}

func (v NullableContainerTypeChangeLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerTypeChangeLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


