/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// ContainerResponse struct for ContainerResponse
type ContainerResponse struct {
	Data *ContainerByIdResponseData `json:"data,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewContainerResponse instantiates a new ContainerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerResponse() *ContainerResponse {
	this := ContainerResponse{}
	return &this
}

// NewContainerResponseWithDefaults instantiates a new ContainerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerResponseWithDefaults() *ContainerResponse {
	this := ContainerResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ContainerResponse) GetData() ContainerByIdResponseData {
	if o == nil || o.Data == nil {
		var ret ContainerByIdResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerResponse) GetDataOk() (*ContainerByIdResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ContainerResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ContainerByIdResponseData and assigns it to the Data field.
func (o *ContainerResponse) SetData(v ContainerByIdResponseData) {
	o.Data = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ContainerResponse) GetRequest() Request {
	if o == nil || o.Request == nil {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerResponse) GetRequestOk() (*Request, bool) {
	if o == nil || o.Request == nil {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ContainerResponse) HasRequest() bool {
	if o != nil && o.Request != nil {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *ContainerResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o ContainerResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullableContainerResponse struct {
	value *ContainerResponse
	isSet bool
}

func (v NullableContainerResponse) Get() *ContainerResponse {
	return v.value
}

func (v *NullableContainerResponse) Set(val *ContainerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerResponse(val *ContainerResponse) *NullableContainerResponse {
	return &NullableContainerResponse{value: val, isSet: true}
}

func (v NullableContainerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


