/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// ReasonsAllSuccessResponse struct for ReasonsAllSuccessResponse
type ReasonsAllSuccessResponse struct {
	Data []ReasonResponse `json:"data,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewReasonsAllSuccessResponse instantiates a new ReasonsAllSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasonsAllSuccessResponse() *ReasonsAllSuccessResponse {
	this := ReasonsAllSuccessResponse{}
	return &this
}

// NewReasonsAllSuccessResponseWithDefaults instantiates a new ReasonsAllSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasonsAllSuccessResponseWithDefaults() *ReasonsAllSuccessResponse {
	this := ReasonsAllSuccessResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ReasonsAllSuccessResponse) GetData() []ReasonResponse {
	if o == nil || o.Data == nil {
		var ret []ReasonResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasonsAllSuccessResponse) GetDataOk() ([]ReasonResponse, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReasonsAllSuccessResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []ReasonResponse and assigns it to the Data field.
func (o *ReasonsAllSuccessResponse) SetData(v []ReasonResponse) {
	o.Data = v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ReasonsAllSuccessResponse) GetRequest() Request {
	if o == nil || o.Request == nil {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasonsAllSuccessResponse) GetRequestOk() (*Request, bool) {
	if o == nil || o.Request == nil {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ReasonsAllSuccessResponse) HasRequest() bool {
	if o != nil && o.Request != nil {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *ReasonsAllSuccessResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o ReasonsAllSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullableReasonsAllSuccessResponse struct {
	value *ReasonsAllSuccessResponse
	isSet bool
}

func (v NullableReasonsAllSuccessResponse) Get() *ReasonsAllSuccessResponse {
	return v.value
}

func (v *NullableReasonsAllSuccessResponse) Set(val *ReasonsAllSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReasonsAllSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReasonsAllSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasonsAllSuccessResponse(val *ReasonsAllSuccessResponse) *NullableReasonsAllSuccessResponse {
	return &NullableReasonsAllSuccessResponse{value: val, isSet: true}
}

func (v NullableReasonsAllSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasonsAllSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


