/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package containerdomain

import (
	"encoding/json"
)

// PutErrorResponse struct for PutErrorResponse
type PutErrorResponse struct {
	Error *Error `json:"error,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewPutErrorResponse instantiates a new PutErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutErrorResponse() *PutErrorResponse {
	this := PutErrorResponse{}
	return &this
}

// NewPutErrorResponseWithDefaults instantiates a new PutErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutErrorResponseWithDefaults() *PutErrorResponse {
	this := PutErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PutErrorResponse) GetError() Error {
	if o == nil || o.Error == nil {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutErrorResponse) GetErrorOk() (*Error, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PutErrorResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *PutErrorResponse) SetError(v Error) {
	o.Error = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *PutErrorResponse) GetRequest() Request {
	if o == nil || o.Request == nil {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutErrorResponse) GetRequestOk() (*Request, bool) {
	if o == nil || o.Request == nil {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *PutErrorResponse) HasRequest() bool {
	if o != nil && o.Request != nil {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *PutErrorResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o PutErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullablePutErrorResponse struct {
	value *PutErrorResponse
	isSet bool
}

func (v NullablePutErrorResponse) Get() *PutErrorResponse {
	return v.value
}

func (v *NullablePutErrorResponse) Set(val *PutErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePutErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePutErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutErrorResponse(val *PutErrorResponse) *NullablePutErrorResponse {
	return &NullablePutErrorResponse{value: val, isSet: true}
}

func (v NullablePutErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


