/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// ContainerTypesResponse struct for ContainerTypesResponse
type ContainerTypesResponse struct {
	Data *ContainerTypesResponseData `json:"data,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewContainerTypesResponse instantiates a new ContainerTypesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerTypesResponse() *ContainerTypesResponse {
	this := ContainerTypesResponse{}
	return &this
}

// NewContainerTypesResponseWithDefaults instantiates a new ContainerTypesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerTypesResponseWithDefaults() *ContainerTypesResponse {
	this := ContainerTypesResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ContainerTypesResponse) GetData() ContainerTypesResponseData {
	if o == nil || o.Data == nil {
		var ret ContainerTypesResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerTypesResponse) GetDataOk() (*ContainerTypesResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ContainerTypesResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ContainerTypesResponseData and assigns it to the Data field.
func (o *ContainerTypesResponse) SetData(v ContainerTypesResponseData) {
	o.Data = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ContainerTypesResponse) GetRequest() Request {
	if o == nil || o.Request == nil {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerTypesResponse) GetRequestOk() (*Request, bool) {
	if o == nil || o.Request == nil {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ContainerTypesResponse) HasRequest() bool {
	if o != nil && o.Request != nil {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *ContainerTypesResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o ContainerTypesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullableContainerTypesResponse struct {
	value *ContainerTypesResponse
	isSet bool
}

func (v NullableContainerTypesResponse) Get() *ContainerTypesResponse {
	return v.value
}

func (v *NullableContainerTypesResponse) Set(val *ContainerTypesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerTypesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerTypesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerTypesResponse(val *ContainerTypesResponse) *NullableContainerTypesResponse {
	return &NullableContainerTypesResponse{value: val, isSet: true}
}

func (v NullableContainerTypesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerTypesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


