/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// ContainerTypeChangeLogAllOf struct for ContainerTypeChangeLogAllOf
type ContainerTypeChangeLogAllOf struct {
	// Container type change log data.
	Cdc map[string]interface{} `json:"cdc"`
}

// NewContainerTypeChangeLogAllOf instantiates a new ContainerTypeChangeLogAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerTypeChangeLogAllOf(cdc map[string]interface{}) *ContainerTypeChangeLogAllOf {
	this := ContainerTypeChangeLogAllOf{}
	this.Cdc = cdc
	return &this
}

// NewContainerTypeChangeLogAllOfWithDefaults instantiates a new ContainerTypeChangeLogAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerTypeChangeLogAllOfWithDefaults() *ContainerTypeChangeLogAllOf {
	this := ContainerTypeChangeLogAllOf{}
	return &this
}

// GetCdc returns the Cdc field value
func (o *ContainerTypeChangeLogAllOf) GetCdc() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Cdc
}

// GetCdcOk returns a tuple with the Cdc field value
// and a boolean to check if the value has been set.
func (o *ContainerTypeChangeLogAllOf) GetCdcOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cdc, true
}

// SetCdc sets field value
func (o *ContainerTypeChangeLogAllOf) SetCdc(v map[string]interface{}) {
	o.Cdc = v
}

func (o ContainerTypeChangeLogAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cdc"] = o.Cdc
	}
	return json.Marshal(toSerialize)
}

type NullableContainerTypeChangeLogAllOf struct {
	value *ContainerTypeChangeLogAllOf
	isSet bool
}

func (v NullableContainerTypeChangeLogAllOf) Get() *ContainerTypeChangeLogAllOf {
	return v.value
}

func (v *NullableContainerTypeChangeLogAllOf) Set(val *ContainerTypeChangeLogAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerTypeChangeLogAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerTypeChangeLogAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerTypeChangeLogAllOf(val *ContainerTypeChangeLogAllOf) *NullableContainerTypeChangeLogAllOf {
	return &NullableContainerTypeChangeLogAllOf{value: val, isSet: true}
}

func (v NullableContainerTypeChangeLogAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerTypeChangeLogAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


