/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// ContainerChangeLogResponse struct for ContainerChangeLogResponse
type ContainerChangeLogResponse struct {
	Error *Error `json:"error,omitempty"`
	Data *ContainerChangeLogResponseData `json:"data,omitempty"`
	Request *Request `json:"request,omitempty"`
}

// NewContainerChangeLogResponse instantiates a new ContainerChangeLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerChangeLogResponse() *ContainerChangeLogResponse {
	this := ContainerChangeLogResponse{}
	return &this
}

// NewContainerChangeLogResponseWithDefaults instantiates a new ContainerChangeLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerChangeLogResponseWithDefaults() *ContainerChangeLogResponse {
	this := ContainerChangeLogResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ContainerChangeLogResponse) GetError() Error {
	if o == nil || o.Error == nil {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerChangeLogResponse) GetErrorOk() (*Error, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ContainerChangeLogResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *ContainerChangeLogResponse) SetError(v Error) {
	o.Error = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ContainerChangeLogResponse) GetData() ContainerChangeLogResponseData {
	if o == nil || o.Data == nil {
		var ret ContainerChangeLogResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerChangeLogResponse) GetDataOk() (*ContainerChangeLogResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ContainerChangeLogResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ContainerChangeLogResponseData and assigns it to the Data field.
func (o *ContainerChangeLogResponse) SetData(v ContainerChangeLogResponseData) {
	o.Data = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ContainerChangeLogResponse) GetRequest() Request {
	if o == nil || o.Request == nil {
		var ret Request
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerChangeLogResponse) GetRequestOk() (*Request, bool) {
	if o == nil || o.Request == nil {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ContainerChangeLogResponse) HasRequest() bool {
	if o != nil && o.Request != nil {
		return true
	}

	return false
}

// SetRequest gets a reference to the given Request and assigns it to the Request field.
func (o *ContainerChangeLogResponse) SetRequest(v Request) {
	o.Request = &v
}

func (o ContainerChangeLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Request != nil {
		toSerialize["request"] = o.Request
	}
	return json.Marshal(toSerialize)
}

type NullableContainerChangeLogResponse struct {
	value *ContainerChangeLogResponse
	isSet bool
}

func (v NullableContainerChangeLogResponse) Get() *ContainerChangeLogResponse {
	return v.value
}

func (v *NullableContainerChangeLogResponse) Set(val *ContainerChangeLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerChangeLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerChangeLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerChangeLogResponse(val *ContainerChangeLogResponse) *NullableContainerChangeLogResponse {
	return &NullableContainerChangeLogResponse{value: val, isSet: true}
}

func (v NullableContainerChangeLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerChangeLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


