/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// Query struct for Query
type Query struct {
	// The match query is the standard query for performing a full-text search.
	Match []Match `json:"match,omitempty"`
	// The multi-match query builds on the match query allows multi-field queries.
	MultiMatch []MultiMatch `json:"multi_match,omitempty"`
	// The Term query returns fields that contain an exact term in a provided field.
	Term []Term `json:"term,omitempty"`
	// The Terms query returns field that contain one or more exact terms in a provided field. The terms query is the same as the term query, except you can search for multiple values.
	Terms []Terms `json:"terms,omitempty"`
	// The Range query returns fields that contain terms within a provided range.
	Range []RangeQuery `json:"range,omitempty"`
	// The Regexp query returns fields that contain terms matching a regular expression.
	Regexp []Regex `json:"regexp,omitempty"`
	Exists []Exists `json:"exists,omitempty"`
	Fuzzy []Fuzzy `json:"fuzzy,omitempty"`
	Prefix []Prefix `json:"prefix,omitempty"`
	Wildcard []Wildcard `json:"wildcard,omitempty"`
	MatchPhrase []MatchPhrase `json:"match_phrase,omitempty"`
	MatchPhrasePrefix []MatchPhrasePrefix `json:"match_phrase_prefix,omitempty"`
}

// NewQuery instantiates a new Query object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuery() *Query {
	this := Query{}
	return &this
}

// NewQueryWithDefaults instantiates a new Query object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryWithDefaults() *Query {
	this := Query{}
	return &this
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *Query) GetMatch() []Match {
	if o == nil || o.Match == nil {
		var ret []Match
		return ret
	}
	return o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetMatchOk() ([]Match, bool) {
	if o == nil || o.Match == nil {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *Query) HasMatch() bool {
	if o != nil && o.Match != nil {
		return true
	}

	return false
}

// SetMatch gets a reference to the given []Match and assigns it to the Match field.
func (o *Query) SetMatch(v []Match) {
	o.Match = v
}

// GetMultiMatch returns the MultiMatch field value if set, zero value otherwise.
func (o *Query) GetMultiMatch() []MultiMatch {
	if o == nil || o.MultiMatch == nil {
		var ret []MultiMatch
		return ret
	}
	return o.MultiMatch
}

// GetMultiMatchOk returns a tuple with the MultiMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetMultiMatchOk() ([]MultiMatch, bool) {
	if o == nil || o.MultiMatch == nil {
		return nil, false
	}
	return o.MultiMatch, true
}

// HasMultiMatch returns a boolean if a field has been set.
func (o *Query) HasMultiMatch() bool {
	if o != nil && o.MultiMatch != nil {
		return true
	}

	return false
}

// SetMultiMatch gets a reference to the given []MultiMatch and assigns it to the MultiMatch field.
func (o *Query) SetMultiMatch(v []MultiMatch) {
	o.MultiMatch = v
}

// GetTerm returns the Term field value if set, zero value otherwise.
func (o *Query) GetTerm() []Term {
	if o == nil || o.Term == nil {
		var ret []Term
		return ret
	}
	return o.Term
}

// GetTermOk returns a tuple with the Term field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetTermOk() ([]Term, bool) {
	if o == nil || o.Term == nil {
		return nil, false
	}
	return o.Term, true
}

// HasTerm returns a boolean if a field has been set.
func (o *Query) HasTerm() bool {
	if o != nil && o.Term != nil {
		return true
	}

	return false
}

// SetTerm gets a reference to the given []Term and assigns it to the Term field.
func (o *Query) SetTerm(v []Term) {
	o.Term = v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *Query) GetTerms() []Terms {
	if o == nil || o.Terms == nil {
		var ret []Terms
		return ret
	}
	return o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetTermsOk() ([]Terms, bool) {
	if o == nil || o.Terms == nil {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *Query) HasTerms() bool {
	if o != nil && o.Terms != nil {
		return true
	}

	return false
}

// SetTerms gets a reference to the given []Terms and assigns it to the Terms field.
func (o *Query) SetTerms(v []Terms) {
	o.Terms = v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *Query) GetRange() []RangeQuery {
	if o == nil || o.Range == nil {
		var ret []RangeQuery
		return ret
	}
	return o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetRangeOk() ([]RangeQuery, bool) {
	if o == nil || o.Range == nil {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *Query) HasRange() bool {
	if o != nil && o.Range != nil {
		return true
	}

	return false
}

// SetRange gets a reference to the given []RangeQuery and assigns it to the Range field.
func (o *Query) SetRange(v []RangeQuery) {
	o.Range = v
}

// GetRegexp returns the Regexp field value if set, zero value otherwise.
func (o *Query) GetRegexp() []Regex {
	if o == nil || o.Regexp == nil {
		var ret []Regex
		return ret
	}
	return o.Regexp
}

// GetRegexpOk returns a tuple with the Regexp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetRegexpOk() ([]Regex, bool) {
	if o == nil || o.Regexp == nil {
		return nil, false
	}
	return o.Regexp, true
}

// HasRegexp returns a boolean if a field has been set.
func (o *Query) HasRegexp() bool {
	if o != nil && o.Regexp != nil {
		return true
	}

	return false
}

// SetRegexp gets a reference to the given []Regex and assigns it to the Regexp field.
func (o *Query) SetRegexp(v []Regex) {
	o.Regexp = v
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *Query) GetExists() []Exists {
	if o == nil || o.Exists == nil {
		var ret []Exists
		return ret
	}
	return o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetExistsOk() ([]Exists, bool) {
	if o == nil || o.Exists == nil {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *Query) HasExists() bool {
	if o != nil && o.Exists != nil {
		return true
	}

	return false
}

// SetExists gets a reference to the given []Exists and assigns it to the Exists field.
func (o *Query) SetExists(v []Exists) {
	o.Exists = v
}

// GetFuzzy returns the Fuzzy field value if set, zero value otherwise.
func (o *Query) GetFuzzy() []Fuzzy {
	if o == nil || o.Fuzzy == nil {
		var ret []Fuzzy
		return ret
	}
	return o.Fuzzy
}

// GetFuzzyOk returns a tuple with the Fuzzy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetFuzzyOk() ([]Fuzzy, bool) {
	if o == nil || o.Fuzzy == nil {
		return nil, false
	}
	return o.Fuzzy, true
}

// HasFuzzy returns a boolean if a field has been set.
func (o *Query) HasFuzzy() bool {
	if o != nil && o.Fuzzy != nil {
		return true
	}

	return false
}

// SetFuzzy gets a reference to the given []Fuzzy and assigns it to the Fuzzy field.
func (o *Query) SetFuzzy(v []Fuzzy) {
	o.Fuzzy = v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *Query) GetPrefix() []Prefix {
	if o == nil || o.Prefix == nil {
		var ret []Prefix
		return ret
	}
	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetPrefixOk() ([]Prefix, bool) {
	if o == nil || o.Prefix == nil {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *Query) HasPrefix() bool {
	if o != nil && o.Prefix != nil {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given []Prefix and assigns it to the Prefix field.
func (o *Query) SetPrefix(v []Prefix) {
	o.Prefix = v
}

// GetWildcard returns the Wildcard field value if set, zero value otherwise.
func (o *Query) GetWildcard() []Wildcard {
	if o == nil || o.Wildcard == nil {
		var ret []Wildcard
		return ret
	}
	return o.Wildcard
}

// GetWildcardOk returns a tuple with the Wildcard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetWildcardOk() ([]Wildcard, bool) {
	if o == nil || o.Wildcard == nil {
		return nil, false
	}
	return o.Wildcard, true
}

// HasWildcard returns a boolean if a field has been set.
func (o *Query) HasWildcard() bool {
	if o != nil && o.Wildcard != nil {
		return true
	}

	return false
}

// SetWildcard gets a reference to the given []Wildcard and assigns it to the Wildcard field.
func (o *Query) SetWildcard(v []Wildcard) {
	o.Wildcard = v
}

// GetMatchPhrase returns the MatchPhrase field value if set, zero value otherwise.
func (o *Query) GetMatchPhrase() []MatchPhrase {
	if o == nil || o.MatchPhrase == nil {
		var ret []MatchPhrase
		return ret
	}
	return o.MatchPhrase
}

// GetMatchPhraseOk returns a tuple with the MatchPhrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetMatchPhraseOk() ([]MatchPhrase, bool) {
	if o == nil || o.MatchPhrase == nil {
		return nil, false
	}
	return o.MatchPhrase, true
}

// HasMatchPhrase returns a boolean if a field has been set.
func (o *Query) HasMatchPhrase() bool {
	if o != nil && o.MatchPhrase != nil {
		return true
	}

	return false
}

// SetMatchPhrase gets a reference to the given []MatchPhrase and assigns it to the MatchPhrase field.
func (o *Query) SetMatchPhrase(v []MatchPhrase) {
	o.MatchPhrase = v
}

// GetMatchPhrasePrefix returns the MatchPhrasePrefix field value if set, zero value otherwise.
func (o *Query) GetMatchPhrasePrefix() []MatchPhrasePrefix {
	if o == nil || o.MatchPhrasePrefix == nil {
		var ret []MatchPhrasePrefix
		return ret
	}
	return o.MatchPhrasePrefix
}

// GetMatchPhrasePrefixOk returns a tuple with the MatchPhrasePrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetMatchPhrasePrefixOk() ([]MatchPhrasePrefix, bool) {
	if o == nil || o.MatchPhrasePrefix == nil {
		return nil, false
	}
	return o.MatchPhrasePrefix, true
}

// HasMatchPhrasePrefix returns a boolean if a field has been set.
func (o *Query) HasMatchPhrasePrefix() bool {
	if o != nil && o.MatchPhrasePrefix != nil {
		return true
	}

	return false
}

// SetMatchPhrasePrefix gets a reference to the given []MatchPhrasePrefix and assigns it to the MatchPhrasePrefix field.
func (o *Query) SetMatchPhrasePrefix(v []MatchPhrasePrefix) {
	o.MatchPhrasePrefix = v
}

func (o Query) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Match != nil {
		toSerialize["match"] = o.Match
	}
	if o.MultiMatch != nil {
		toSerialize["multi_match"] = o.MultiMatch
	}
	if o.Term != nil {
		toSerialize["term"] = o.Term
	}
	if o.Terms != nil {
		toSerialize["terms"] = o.Terms
	}
	if o.Range != nil {
		toSerialize["range"] = o.Range
	}
	if o.Regexp != nil {
		toSerialize["regexp"] = o.Regexp
	}
	if o.Exists != nil {
		toSerialize["exists"] = o.Exists
	}
	if o.Fuzzy != nil {
		toSerialize["fuzzy"] = o.Fuzzy
	}
	if o.Prefix != nil {
		toSerialize["prefix"] = o.Prefix
	}
	if o.Wildcard != nil {
		toSerialize["wildcard"] = o.Wildcard
	}
	if o.MatchPhrase != nil {
		toSerialize["match_phrase"] = o.MatchPhrase
	}
	if o.MatchPhrasePrefix != nil {
		toSerialize["match_phrase_prefix"] = o.MatchPhrasePrefix
	}
	return json.Marshal(toSerialize)
}

type NullableQuery struct {
	value *Query
	isSet bool
}

func (v NullableQuery) Get() *Query {
	return v.value
}

func (v *NullableQuery) Set(val *Query) {
	v.value = val
	v.isSet = true
}

func (v NullableQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuery(val *Query) *NullableQuery {
	return &NullableQuery{value: val, isSet: true}
}

func (v NullableQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


