/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// CreationStatus Define the creation status of Container Type.
type CreationStatus struct {
	Status *Status `json:"status,omitempty"`
}

// NewCreationStatus instantiates a new CreationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreationStatus() *CreationStatus {
	this := CreationStatus{}
	return &this
}

// NewCreationStatusWithDefaults instantiates a new CreationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreationStatusWithDefaults() *CreationStatus {
	this := CreationStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreationStatus) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreationStatus) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreationStatus) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *CreationStatus) SetStatus(v Status) {
	o.Status = &v
}

func (o CreationStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableCreationStatus struct {
	value *CreationStatus
	isSet bool
}

func (v NullableCreationStatus) Get() *CreationStatus {
	return v.value
}

func (v *NullableCreationStatus) Set(val *CreationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCreationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCreationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreationStatus(val *CreationStatus) *NullableCreationStatus {
	return &NullableCreationStatus{value: val, isSet: true}
}

func (v NullableCreationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


