/*
Container Service

**API documentation for Container Service**

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package container_client

import (
	"encoding/json"
)

// BatchResponse struct for BatchResponse
type BatchResponse struct {
	Meta *BatchResponseMetaData `json:"meta,omitempty"`
	Errors []BatchRecordError `json:"errors,omitempty"`
	Success []BatchResponseSuccess `json:"success,omitempty"`
}

// NewBatchResponse instantiates a new BatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResponse() *BatchResponse {
	this := BatchResponse{}
	return &this
}

// NewBatchResponseWithDefaults instantiates a new BatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResponseWithDefaults() *BatchResponse {
	this := BatchResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BatchResponse) GetMeta() BatchResponseMetaData {
	if o == nil || o.Meta == nil {
		var ret BatchResponseMetaData
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetMetaOk() (*BatchResponseMetaData, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BatchResponse) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given BatchResponseMetaData and assigns it to the Meta field.
func (o *BatchResponse) SetMeta(v BatchResponseMetaData) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *BatchResponse) GetErrors() []BatchRecordError {
	if o == nil || o.Errors == nil {
		var ret []BatchRecordError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetErrorsOk() ([]BatchRecordError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BatchResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []BatchRecordError and assigns it to the Errors field.
func (o *BatchResponse) SetErrors(v []BatchRecordError) {
	o.Errors = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *BatchResponse) GetSuccess() []BatchResponseSuccess {
	if o == nil || o.Success == nil {
		var ret []BatchResponseSuccess
		return ret
	}
	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetSuccessOk() ([]BatchResponseSuccess, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *BatchResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given []BatchResponseSuccess and assigns it to the Success field.
func (o *BatchResponse) SetSuccess(v []BatchResponseSuccess) {
	o.Success = v
}

func (o BatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableBatchResponse struct {
	value *BatchResponse
	isSet bool
}

func (v NullableBatchResponse) Get() *BatchResponse {
	return v.value
}

func (v *NullableBatchResponse) Set(val *BatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResponse(val *BatchResponse) *NullableBatchResponse {
	return &NullableBatchResponse{value: val, isSet: true}
}

func (v NullableBatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


